language: r
cache: packages
pandoc_version: 2.7.3

r_packages:
  - devtools
  - knitr
  - formatR
  - kableExtra

before_install:
  - sudo apt-get update -qq
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
  - sudo apt-get install ttf-mscorefonts-installer
  - sudo fc-cache
- sudo apt-get install -y texlive-full
#  - mkdir -p ~/.fonts/
#  - cp -rf fonts/* ~/.fonts/
#  - sudo fc-cache -f -v

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
